a = input('Digite algo:')
print('O tipo primitivo desse vale {}'.format(type(a)))
print('Só tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabeto? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em maiusculas? ', a.isupper())
print('Esta em minusculas? ', a.islower())
print('Está capitalizada? ', a.istitle())